version: '3'
services:
  odm:
   platform: linux/arm64
   image: ibmcom/odm
   container_name: odmResOnDocker
   ports:
   - 9443:9443
   - 9060:9060
   volumes:
   - $PWD:/config/dbdata/
   environment:
     - LICENSE=accept
     - SAMPLE=false
   deploy:
     resources:
       limits:
         memory: 4096M
       reservations:
         memory: 4096M
